export enum ActionTypes {
  FETCH_ALL_WINNERS = "FETCH_ALL_WINNERS",
  VERIFY_WIN_STATUS = "VERIFY_WIN_STATUS",
  CHECK_USER_ELIGIBILITY = "CHECK_USER_ELIGIBILITY",
  SWITCH_TO_THE_NEXT_DAY = "SWITCH_TO_THE_NEXT_DAY",
}
