export enum GetterTypes {
  IS_PLAYER_STATUS_AVAILABLE = "IS_WIN_STATUS_AVAILABLE",
  GET_WINNER = "GET_WINNER",
  GET_CURRENT_PLAYER_FROM_COLLECTION = "GET_CURRENT_PLAYER_FROM_COLLECTION",
  IS_PLAYER_WINNER = "IS_PLAYER_WINNER",
  IS_PLAYER_DUPLICATE = "IS_PLAYER_DUPLICATE",
  IS_WINNERS_REQUEST_FAILED = "IS_WINNERS_REQUEST_FAILED",
}
